### PR TITLE
Reload page when the websocket reconnects

### PR DESCRIPTION
**Pull request by ursi**
This fixes the issue where the client misses all of the websocket events that happened while it was disconnected.

### CODE REVIEW

**Comment by ursi** [comment]
hold up, forgot to lint. I know the quotes are wrong at least.

**Comment by ursi** [comment]
You can test it by going into the network dev tools and turning off access. after waiting around a minute the socket will disconnect, and will not receive any messages that were sent while it was disconnected. I went with a refresh because it is an easy way to make sure all the bases are covered (all my games, players online, games in the lobby, etc.). I think if you don't want to refresh then the code should be refactored so that the initial data all comes from the websocket and not an http requests, so we can be sure we don't miss anything.

**Comment by ursi** [comment]
I updated it so it still refreshes after a reconnect, but not when the disconnect was planned, such as in the case of logging in/out

**Comment by alcalyn** [comment]
It occured today:

```
ArekKulczycki: there seems to be something going on with the websocket at times
Alcalyn: what do you mean with websockets?
ArekKulczycki: disconnection or something, I havent looked into browser console output, but I had to reload the page a couple of times since we started
```

https://playhex.org/games/08d05923-098d-41bd-b85a-f25eee88ae38

It occured multiple times. I have not tried it deeply yet, it should not refresh browser multiple times when playing

**Comment by ursi** [comment]
well, it should only refresh on a true disconnect - where you lose connection for more than a minute*. anything less and the events you missed will be buffered and you'll receive them all when reconnecting. And sure, refresh isn't the best UX, but it's a lot better than missing events, potentially without even realizing it. FlyPside has mentioned losing games because of it.

**Pull request merged**
